student=str(input("student name"))
clas=str(input('class '))
sec=str(input('section '))
english=int(input('english subject mark '))
urdu=int(input('urdu subject mark '))
math=int(input('math subject mark '))
science=int(input('science subject mark '))
socialscience=int(input('social science subject mark '))
total=english+urdu+math+science+socialscience
average=(english+urdu+math+science+socialscience)/5.0
print()
print()
print()
print('                Rakhshinda Public Secondary School')
print('              _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _')
print('                     Half Yearly Exam Result')
print('              _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _')
print('             student name:',student,'class:',clas,'sec:',sec)
print()
print('                     English          :    ',english)
print('                     Urdu             :    ',urdu)
print('                     Math             :    ',math)
print('                     Science          :    ',science)
print('                     Social science   :    ',socialscience)
print()
print('                           Total      :    ',total,'out of 500')
print("                           Average    :    ",average,'%')
print()
if(english<35)or(urdu<35)or(math<35)or(science<35)or(socialscience<35):
    print("                          Result:       Fail")
else:
        print('                      Result:        Pass')